"""Writes a root .env for `docker compose` with fresh random secrets. Never overwrites a secret that already exists:
run against an existing .env it only adds the settings a newer version needs (existing data stays readable).

    python deploy/gen_env.py [--demo]      # --demo also seeds the demo accounts (never for real use)

Keep the file private: SDMS_MASTER_KEY encrypts every stored document, and losing it makes them unreadable.
"""
from __future__ import annotations

import base64
import os
import pathlib
import secrets
import sys

root = pathlib.Path(__file__).resolve().parent.parent
target = root / ".env"
demo = "--demo" in sys.argv

SETTINGS = {
    "SDMS_PG_PASSWORD": lambda: secrets.token_urlsafe(24),         # database admin: used only by db-init
    "SDMS_MONGO_PASSWORD": lambda: secrets.token_urlsafe(24),      # database admin: used only by db-init
    "SDMS_PG_APP_PASSWORD": lambda: secrets.token_urlsafe(24),     # least-privilege account the backend uses
    "SDMS_MONGO_APP_PASSWORD": lambda: secrets.token_urlsafe(24),  # least-privilege account the backend uses
    "SDMS_MASTER_KEY": lambda: base64.b64encode(secrets.token_bytes(32)).decode(),
    "SDMS_JWT_SECRET": lambda: secrets.token_urlsafe(48),
    "SDMS_FABRIC_GATEWAY_KEY": lambda: secrets.token_urlsafe(32),
    "SDMS_AI_SERVICE_KEY": lambda: secrets.token_urlsafe(32),
    "SDMS_SEED_DEMO": lambda: "true" if demo else "false",
}

if target.exists():
    present = {line.split("=", 1)[0].strip() for line in target.read_text(encoding="utf-8").splitlines() if "=" in line}
    missing = [k for k in SETTINGS if k not in present]
    if not missing:
        print(f"{target} already has every setting - nothing to do")
    else:
        text = target.read_text(encoding="utf-8")
        added = "".join(f"{k}={SETTINGS[k]()}\n" for k in missing)
        target.write_text(text + ("" if text.endswith("\n") else "\n") + added, encoding="utf-8")
        print(f"added {', '.join(missing)} to {target} (existing secrets untouched)")
else:
    lines = ["# Generated by deploy/gen_env.py - keep private, never commit."]
    lines += [f"{k}={make()}" for k, make in SETTINGS.items()]
    lines.append("# OLLAMA_URL=http://host.docker.internal:11434")
    target.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {target} ({len(SETTINGS)} settings)" + ("  [demo accounts enabled]" if demo else ""))

os.chmod(target, 0o600)  # owner-only on Linux/macOS; on Windows this only clears the read-only flag
