"""Writes a root .env for `docker compose` with fresh random secrets. Refuses to overwrite an existing one.

    python deploy/gen_env.py [--demo]      # --demo also seeds the demo accounts (never for real use)

Keep the file private: SDMS_MASTER_KEY encrypts every stored document, and losing it makes them unreadable.
"""
from __future__ import annotations

import base64
import pathlib
import secrets
import sys

root = pathlib.Path(__file__).resolve().parent.parent
target = root / ".env"
if target.exists():
    sys.exit(f"{target} already exists - not overwriting it (delete it first if you really want new secrets; existing data would become unreadable)")

demo = "--demo" in sys.argv
lines = [
    "# Generated by deploy/gen_env.py - keep private, never commit.",
    f"SDMS_PG_PASSWORD={secrets.token_urlsafe(24)}",
    f"SDMS_MONGO_PASSWORD={secrets.token_urlsafe(24)}",
    f"SDMS_MASTER_KEY={base64.b64encode(secrets.token_bytes(32)).decode()}",
    f"SDMS_JWT_SECRET={secrets.token_urlsafe(48)}",
    f"SDMS_FABRIC_GATEWAY_KEY={secrets.token_urlsafe(32)}",
    f"SDMS_AI_SERVICE_KEY={secrets.token_urlsafe(32)}",
    f"SDMS_SEED_DEMO={'true' if demo else 'false'}",
    "# OLLAMA_URL=http://host.docker.internal:11434",
]
target.write_text("\n".join(lines) + "\n", encoding="utf-8")
print(f"wrote {target} ({len(lines) - 2} settings)" + ("  [demo accounts enabled]" if demo else ""))
